// Fallback data for when the database is not available

import { blogContent } from "./blog-content"


export const fallbackBlogs = [
  {
    _id: "blog-1",
    title: "How I Built a CAD Reconstruction Engine with OpenCASCADE and GPT-4o Vision",
    slug: "cad-reconstruction-opencascade-gpt4o-vision",
    excerpt: "A deep dive into ForgeCadNeo — converting 2D engineering drawings to manufacturing-grade 3D STEP files using AI vision and B-Rep solid modeling, reducing hours of manual CAD work to minutes.",
    content: blogContent["blog-1"],
    image: "",
    category: "Case Study",
    tags: ["OpenCASCADE", "GPT-4o", "FastAPI", "Three.js", "Python"],
    author: "Abhishek Sharma",
    date: "Mar 15, 2026",
    readTime: "12 min read",
    isPublished: true,
    featured: true,
    createdAt: "2026-03-15T10:00:00.000Z",
    updatedAt: "2026-03-15T10:00:00.000Z",
    seo: { metaTitle: "Building a CAD Reconstruction Engine with OpenCASCADE and GPT-4o Vision", metaDescription: "How ForgeCadNeo converts 2D engineering drawings to 3D STEP files using AI vision and B-Rep solid modeling.", keywords: ["OpenCASCADE", "GPT-4o", "CAD", "3D modeling", "AI vision"], canonicalUrl: "" },
  },
  {
    _id: "blog-2",
    title: "Building 40+ AI Agents with LangChain for an Enterprise Recruitment Platform",
    slug: "langchain-ai-agents-recruitment-platform",
    excerpt: "How I architected a multi-agent system with LangChain for resume matching, culture-fit scoring, and predictive retention — with Groq as the primary LLM provider for cost efficiency.",
    content: blogContent["blog-2"],
    image: "",
    category: "AI & ML",
    tags: ["LangChain", "Groq", "Next.js", "PostgreSQL", "AI Agents"],
    author: "Abhishek Sharma",
    date: "Mar 1, 2026",
    readTime: "10 min read",
    isPublished: true,
    featured: true,
    createdAt: "2026-03-01T10:00:00.000Z",
    updatedAt: "2026-03-01T10:00:00.000Z",
    seo: { metaTitle: "Building 40+ AI Agents with LangChain for Enterprise Recruitment", metaDescription: "Architecting a multi-agent LangChain system for resume matching, culture-fit scoring, and predictive retention.", keywords: ["LangChain", "AI agents", "recruitment", "Groq"], canonicalUrl: "" },
  },
  {
    _id: "blog-3",
    title: "Real-Time Delivery Tracking with NestJS, Socket.IO, and PostGIS",
    slug: "realtime-delivery-tracking-nestjs-socketio-postgis",
    excerpt: "Building Errandoo's real-time GPS tracking system — from WebSocket architecture to PostGIS spatial queries for finding nearby riders within a 5km radius.",
    content: blogContent["blog-3"],
    image: "",
    category: "Backend",
    tags: ["NestJS", "Socket.IO", "PostGIS", "BullMQ", "Real-time"],
    author: "Abhishek Sharma",
    date: "Feb 15, 2026",
    readTime: "9 min read",
    isPublished: true,
    featured: true,
    createdAt: "2026-02-15T10:00:00.000Z",
    updatedAt: "2026-02-15T10:00:00.000Z",
    seo: { metaTitle: "Real-Time Delivery Tracking with NestJS, Socket.IO, and PostGIS", metaDescription: "Building a real-time GPS tracking system with WebSockets, spatial queries, and background job processing.", keywords: ["NestJS", "Socket.IO", "PostGIS", "real-time"], canonicalUrl: "" },
  },
  {
    _id: "blog-4",
    title: "Migrating a Legacy Pug/Express App to React + NestJS: An 85% Performance Gain",
    slug: "migrating-pug-express-to-react-nestjs-performance",
    excerpt: "A case study on migrating a large-scale competitive intelligence application from server-rendered Pug templates to a React SPA with NestJS backend, achieving 85% faster page loads.",
    content: blogContent["blog-4"],
    image: "",
    category: "Case Study",
    tags: ["React", "NestJS", "Cerbos", "Migration", "Performance"],
    author: "Abhishek Sharma",
    date: "Feb 1, 2026",
    readTime: "14 min read",
    isPublished: true,
    featured: false,
    createdAt: "2026-02-01T10:00:00.000Z",
    updatedAt: "2026-02-01T10:00:00.000Z",
    seo: { metaTitle: "Migrating Pug/Express to React + NestJS: 85% Performance Gain", metaDescription: "Case study on migrating a legacy application to modern React + NestJS architecture.", keywords: ["migration", "React", "NestJS", "performance", "Cerbos"], canonicalUrl: "" },
  },
  {
    _id: "blog-5",
    title: "Deploying Full-Stack Apps on a Single VPS: Docker, Nginx, and Let's Encrypt",
    slug: "deploying-fullstack-apps-single-vps-docker-nginx",
    excerpt: "A practical guide to deploying Next.js + NestJS + PostgreSQL applications on a single VPS with Docker Compose, Nginx reverse proxy, and automatic SSL.",
    content: blogContent["blog-5"],
    image: "",
    category: "DevOps",
    tags: ["Docker", "Nginx", "VPS", "PostgreSQL", "Let's Encrypt"],
    author: "Abhishek Sharma",
    date: "Jan 15, 2026",
    readTime: "15 min read",
    isPublished: true,
    featured: false,
    createdAt: "2026-01-15T10:00:00.000Z",
    updatedAt: "2026-01-15T10:00:00.000Z",
    seo: { metaTitle: "Deploying Full-Stack Apps on a Single VPS with Docker and Nginx", metaDescription: "Practical guide to deploying apps on a single VPS with Docker Compose and Nginx.", keywords: ["Docker", "Nginx", "VPS", "deployment"], canonicalUrl: "" },
  },
  {
    _id: "blog-6",
    title: "Building a Multi-Tenant Healthcare Platform with Angular and Sequelize",
    slug: "multi-tenant-healthcare-platform-angular-sequelize",
    excerpt: "Lessons from building Prevadu Health — a radiology appointment platform with 27 master data modules, role-based dashboards, and SuperPay payment integration.",
    content: blogContent["blog-6"],
    image: "",
    category: "Case Study",
    tags: ["Angular", "Node.js", "Sequelize", "Healthcare", "Multi-tenant"],
    author: "Abhishek Sharma",
    date: "Jan 1, 2026",
    readTime: "16 min read",
    isPublished: true,
    featured: false,
    createdAt: "2026-01-01T10:00:00.000Z",
    updatedAt: "2026-01-01T10:00:00.000Z",
    seo: { metaTitle: "Building a Multi-Tenant Healthcare Platform with Angular and Sequelize", metaDescription: "Case study on Prevadu Health — a radiology platform with multi-tenancy, RBAC, and payment integration.", keywords: ["Angular", "healthcare", "multi-tenant", "Sequelize"], canonicalUrl: "" },
  },
  {
    _id: "blog-7",
    title: "Prisma vs Sequelize vs TypeORM: Choosing the Right Node.js ORM in 2026",
    slug: "prisma-vs-sequelize-vs-typeorm-nodejs-orm-2026",
    excerpt: "After using all three ORMs in production — Prisma in Errandoo, Sequelize in Prevadu, TypeORM in older projects — here's an honest comparison with real-world trade-offs.",
    content: blogContent["blog-7"],
    image: "",
    category: "Backend",
    tags: ["Prisma", "Sequelize", "TypeORM", "Node.js", "PostgreSQL"],
    author: "Abhishek Sharma",
    date: "Dec 15, 2025",
    readTime: "14 min read",
    isPublished: true,
    featured: false,
    createdAt: "2025-12-15T10:00:00.000Z",
    updatedAt: "2025-12-15T10:00:00.000Z",
    seo: { metaTitle: "Prisma vs Sequelize vs TypeORM: Node.js ORM Comparison 2026", metaDescription: "Honest comparison of Prisma, Sequelize, and TypeORM based on real production experience.", keywords: ["Prisma", "Sequelize", "TypeORM", "ORM", "Node.js"], canonicalUrl: "" },
  },
  {
    _id: "blog-8",
    title: "Adding Interactive 3D to Web Apps with React Three Fiber and Drei",
    slug: "interactive-3d-react-three-fiber-drei",
    excerpt: "How I integrated Three.js into production web apps — from product viewers in Cygnet Design to CAD visualization in ForgeCadNeo.",
    content: blogContent["blog-8"],
    image: "",
    category: "Frontend",
    tags: ["Three.js", "React Three Fiber", "WebGL", "3D", "React"],
    author: "Abhishek Sharma",
    date: "Dec 1, 2025",
    readTime: "13 min read",
    isPublished: true,
    featured: false,
    createdAt: "2025-12-01T10:00:00.000Z",
    updatedAt: "2025-12-01T10:00:00.000Z",
    seo: { metaTitle: "Interactive 3D in Web Apps with React Three Fiber and Drei", metaDescription: "Practical guide to adding Three.js 3D rendering to React apps.", keywords: ["Three.js", "React Three Fiber", "Drei", "WebGL"], canonicalUrl: "" },
  },
  {
    _id: "blog-9",
    title: "Implementing OTP Authentication Without Firebase: SMS, Rate Limiting, and Security",
    slug: "otp-authentication-without-firebase-sms-rate-limiting",
    excerpt: "A production-ready OTP authentication flow using Fast2SMS, Redis-backed rate limiting, and JWT refresh token rotation — no Firebase dependency required.",
    content: blogContent["blog-9"],
    image: "",
    category: "Security",
    tags: ["Authentication", "OTP", "Redis", "JWT", "Node.js"],
    author: "Abhishek Sharma",
    date: "Nov 15, 2025",
    readTime: "16 min read",
    isPublished: true,
    featured: false,
    createdAt: "2025-11-15T10:00:00.000Z",
    updatedAt: "2025-11-15T10:00:00.000Z",
    seo: { metaTitle: "OTP Authentication Without Firebase: SMS, Rate Limiting, and Security", metaDescription: "Building production-ready phone OTP auth with Fast2SMS, Redis rate limiting, and JWT token rotation.", keywords: ["OTP", "authentication", "SMS", "Redis", "JWT"], canonicalUrl: "" },
  },
  {
    _id: "blog-10",
    title: "pnpm Workspaces + Turborepo: Structuring a Full-Stack Monorepo",
    slug: "pnpm-workspaces-turborepo-fullstack-monorepo",
    excerpt: "How I structure monorepos for full-stack TypeScript projects with shared types, validators, and config packages.",
    content: blogContent["blog-10"],
    image: "",
    category: "Architecture",
    tags: ["pnpm", "Turborepo", "Monorepo", "TypeScript", "NestJS"],
    author: "Abhishek Sharma",
    date: "Nov 1, 2025",
    readTime: "7 min read",
    isPublished: true,
    featured: false,
    createdAt: "2025-11-01T10:00:00.000Z",
    updatedAt: "2025-11-01T10:00:00.000Z",
    seo: { metaTitle: "pnpm Workspaces + Turborepo: Structuring a Full-Stack Monorepo", metaDescription: "How to structure monorepos for full-stack TypeScript projects.", keywords: ["pnpm", "Turborepo", "monorepo", "TypeScript"], canonicalUrl: "" },
  },
  {
    _id: "blog-11",
    title: "Automating Lead Generation with Python Agents and n8n Workflows",
    slug: "automating-lead-generation-python-agents-n8n",
    excerpt: "How LeadsNeoForge uses autonomous Python agents for Reddit monitoring, LinkedIn outreach, and content scheduling — orchestrated through n8n workflow automation.",
    content: blogContent["blog-11"],
    image: "",
    category: "Full Stack",
    tags: ["Python", "n8n", "Groq", "Automation", "Lead Generation"],
    author: "Abhishek Sharma",
    date: "Oct 15, 2025",
    readTime: "8 min read",
    isPublished: true,
    featured: false,
    createdAt: "2025-10-15T10:00:00.000Z",
    updatedAt: "2025-10-15T10:00:00.000Z",
    seo: { metaTitle: "Automating Lead Generation with Python Agents and n8n Workflows", metaDescription: "Building autonomous lead generation with Python agents, Groq LLM, and n8n workflow automation.", keywords: ["Python", "automation", "lead generation", "n8n", "Groq"], canonicalUrl: "" },
  },
  {
    _id: "blog-12",
    title: "GSAP ScrollTrigger vs Framer Motion: When to Use Each in Next.js",
    slug: "gsap-scrolltrigger-vs-framer-motion-nextjs",
    excerpt: "After using both animation libraries extensively in production — GSAP in Appnly, Framer Motion in this portfolio — here's when each shines and how to combine them.",
    content: blogContent["blog-12"],
    image: "",
    category: "Frontend",
    tags: ["GSAP", "Framer Motion", "Animation", "Next.js", "ScrollTrigger"],
    author: "Abhishek Sharma",
    date: "Oct 1, 2025",
    readTime: "6 min read",
    isPublished: true,
    featured: false,
    createdAt: "2025-10-01T10:00:00.000Z",
    updatedAt: "2025-10-01T10:00:00.000Z",
    seo: { metaTitle: "GSAP ScrollTrigger vs Framer Motion: When to Use Each in Next.js", metaDescription: "Practical comparison of GSAP and Framer Motion for web animations.", keywords: ["GSAP", "Framer Motion", "animation", "ScrollTrigger"], canonicalUrl: "" },
  },
]

export const fallbackProjects = [
  {
    _id: "proj-forgecadneo",
    title: "ForgeCadNeo",
    description: "AI-powered CAD reconstruction platform that converts 2D engineering drawings into manufacturing-grade 3D STEP files. Uses OpenCASCADE B-Rep kernel with GPT-4o vision to extract dimensions, tolerances, and features — reducing 2-8 hours of manual CAD work to ~15 minutes.",
    image: "https://res.cloudinary.com/duhyrtr2h/image/upload/v1775497406/forgecadneo_xwwq0z.png",
    mediaType: "image",
    category: "fullstack",
    tags: ["React", "FastAPI", "Three.js", "OpenCASCADE", "OpenAI"],
    demoUrl: "https://forgecadneo.neocodehub.com",
    sourceUrl: "",
    featured: true,
    createdAt: "2025-06-01T10:00:00.000Z",
    updatedAt: "2026-04-04T10:00:00.000Z",
  },
  {
    _id: "proj-recruitpro",
    title: "NCHRecruitPro",
    description: "Enterprise AI-powered Applicant Tracking System and HRM platform with 40+ LangChain agents for resume matching, culture-fit scoring, predictive retention, and skill gap analysis. Features multi-tenant architecture, lead discovery crawlers, payroll, and real-time analytics.",
    image: "https://res.cloudinary.com/duhyrtr2h/image/upload/v1775497406/nchrecruitpro_gxivu9.png",
    mediaType: "image",
    category: "fullstack",
    tags: ["Next.js", "LangChain", "PostgreSQL", "Groq", "Docker"],
    demoUrl: "https://nchrecruitpro.neocodehub.com",
    sourceUrl: "",
    featured: true,
    createdAt: "2025-08-01T10:00:00.000Z",
    updatedAt: "2026-04-04T10:00:00.000Z",
  },
  {
    _id: "proj-errandoo",
    title: "Errandoo",
    description: "Hyperlocal on-demand delivery and errand platform with real-time GPS tracking, in-task chat, OTP-verified handoffs, and Cashfree payments. Full-stack monorepo with Next.js web app, NestJS API, Flutter mobile app, and comprehensive monitoring stack (Grafana, Loki, Sentry).",
    image: "https://res.cloudinary.com/duhyrtr2h/image/upload/v1775497414/errandoo_kvl3zk.png",
    mediaType: "image",
    category: "fullstack",
    tags: ["Next.js", "NestJS", "Flutter", "PostgreSQL", "Socket.IO"],
    demoUrl: "https://errandoo.neocodehub.com",
    sourceUrl: "",
    featured: true,
    createdAt: "2026-01-01T10:00:00.000Z",
    updatedAt: "2026-04-04T10:00:00.000Z",
  },
  {
    _id: "proj-prevadu",
    title: "Prevadu Health",
    description: "Comprehensive radiology and healthcare appointment management platform with patient portal, radiologist dashboard, and admin suite. Supports 27 master data modules, SuperPay payment gateway, Firebase push notifications, Microsoft 365 OAuth email, and SMS-based OTP authentication.",
    image: "https://res.cloudinary.com/duhyrtr2h/image/upload/v1775497410/prevadu_uuefpm.png",
    mediaType: "image",
    category: "fullstack",
    tags: ["Angular", "Node.js", "MySQL", "Sequelize", "Firebase"],
    demoUrl: "",
    sourceUrl: "",
    featured: true,
    createdAt: "2025-03-01T10:00:00.000Z",
    updatedAt: "2026-02-01T10:00:00.000Z",
  },
  {
    _id: "proj-appnly",
    title: "Appnly",
    description: "Professional service platform for Google Workspace migration and automation. Offers zero-downtime email migrations from legacy systems, Google Sheets/AppSheet automation, and DNS/email authentication setup. Trusted by 300+ clients and 20,000+ users globally.",
    image: "https://res.cloudinary.com/duhyrtr2h/image/upload/v1775497405/appnly_azb7tf.png",
    mediaType: "image",
    category: "frontend",
    tags: ["Next.js", "GSAP", "Framer Motion", "EmailJS", "Tailwind"],
    demoUrl: "https://www.appnly.com",
    sourceUrl: "",
    featured: false,
    createdAt: "2025-04-01T10:00:00.000Z",
    updatedAt: "2025-06-19T10:00:00.000Z",
  },
  {
    _id: "proj-cygnet",
    title: "Cygnet Design",
    description: "Product design and engineering services platform for a Pune-based firm with 27+ years of experience. Features interactive 3D model viewer using Three.js, project portfolio with video demonstrations, blog system with CMS, and admin dashboard with analytics — serving automotive, construction, agriculture, and EV design industries.",
    image: "https://res.cloudinary.com/duhyrtr2h/image/upload/v1775497409/cygnet_eabpgn.png",
    mediaType: "image",
    category: "fullstack",
    tags: ["Next.js", "Three.js", "MongoDB", "NextAuth", "Recharts"],
    demoUrl: "",
    sourceUrl: "",
    featured: false,
    createdAt: "2025-05-01T10:00:00.000Z",
    updatedAt: "2025-05-01T10:00:00.000Z",
  },
  {
    _id: "proj-toofi",
    title: "Tooffi",
    description: "Personalized cakes and gifts marketplace connecting customers with passionate bakers and artisans. Features advanced filtering by flavor, occasion, and dietary preferences (vegan, gluten-free, sugar-free), baker profiles with ratings, location-based delivery, and OTP-based phone authentication.",
    image: "https://res.cloudinary.com/duhyrtr2h/image/upload/v1775497406/tooffi_j3nlfi.png",
    mediaType: "image",
    category: "frontend",
    tags: ["Next.js", "Tailwind", "Leaflet", "SWR", "Storybook"],
    demoUrl: "",
    sourceUrl: "",
    featured: false,
    createdAt: "2025-07-01T10:00:00.000Z",
    updatedAt: "2026-01-01T10:00:00.000Z",
  },
  {
    _id: "proj-leadsneoforge",
    title: "LeadsNeoForge",
    description: "AI-powered lead generation and marketing automation platform with autonomous Python agents for Reddit/LinkedIn/Twitter outreach. Features n8n-backed workflow automation, Groq LLM content generation, multi-platform campaign scheduling, and real-time metrics tracking dashboard.",
    image: "https://res.cloudinary.com/duhyrtr2h/image/upload/v1775497409/leadsforge_e31gyz.png",
    mediaType: "image",
    category: "fullstack",
    tags: ["Next.js", "NextAuth", "Groq", "n8n", "Python"],
    demoUrl: "https://leadsneoforge.neocodehub.com",
    sourceUrl: "",
    featured: false,
    createdAt: "2025-09-01T10:00:00.000Z",
    updatedAt: "2026-03-01T10:00:00.000Z",
  },
  {
    _id: "proj-neocodehub",
    title: "NeoCodeHub",
    description: "Digital development agency portfolio with interactive Three.js 3D scenes, personalized proposal URL generator for client-specific pitches, Cloudinary-powered media management, blog platform, and admin dashboard. Supports dynamic proposal links with parameters for client name, company, and service type.",
    image: "https://res.cloudinary.com/duhyrtr2h/image/upload/v1775497408/neocodehub_wk2kjs.png",
    mediaType: "image",
    category: "fullstack",
    tags: ["Next.js", "Three.js", "Cloudinary", "Framer Motion", "Tailwind"],
    demoUrl: "https://neocodehub.com",
    sourceUrl: "",
    featured: false,
    createdAt: "2025-10-01T10:00:00.000Z",
    updatedAt: "2026-04-01T10:00:00.000Z",
  },
]

export const fallbackTestimonials = [
  {
    _id: "test1",
    name: "Abhijatya Kashyap",
    position: "Director",
    company: "Kashyap Enterprises",
    content:
      "Abhishek built our entire company website from scratch using React. He understood our requirements perfectly, delivered a clean and professional design, and was very responsive throughout the project. The final product exceeded our expectations — highly recommended for any web development work.",
    rating: 5,
    image: "/placeholder.svg?height=100&width=100",
    featured: true,
    createdAt: "2023-08-15T10:00:00.000Z",
    updatedAt: "2023-08-15T10:00:00.000Z",
  },
  {
    _id: "test2",
    name: "Raj Shakya",
    position: "Client",
    company: "Upwork",
    content:
      "I hired Abhishek for two separate projects — a voice language evaluation application and a YouTube stats app — and he delivered exceptional work on both. His technical skills in React and Node.js are top-notch, he communicates clearly, and he consistently meets deadlines. Will definitely hire again for future projects.",
    rating: 5,
    image: "/placeholder.svg?height=100&width=100",
    featured: true,
    createdAt: "2023-04-20T10:00:00.000Z",
    updatedAt: "2023-04-20T10:00:00.000Z",
  },
  {
    _id: "test3",
    name: "Nirat",
    position: "Client",
    company: "Upwork",
    content:
      "Abhishek developed a Twitter data aggregation tool for me with sorting, filtering, and CSV export functionality. He has a solid understanding of full-stack development, wrote clean maintainable code, and was proactive about suggesting improvements. Great experience working with him — 5 stars all the way.",
    rating: 5,
    image: "/placeholder.svg?height=100&width=100",
    featured: true,
    createdAt: "2023-06-10T10:00:00.000Z",
    updatedAt: "2023-06-10T10:00:00.000Z",
  },
]

// Export work experience and education separately as required
export const fallbackWorkExperience = [
  {
    _id: "exp1",
    title: "Software Engineer",
    company: "PharmaEdge.ai",
    location: "Remote",
    period: "Dec 2024 - Present",
    description:
      "Designed and developed a full-stack conference platform from scratch using Next.js and PostgreSQL, with an admin panel to monitor user registrations, track exports, and verify users via OTP-based authentication. Implemented multi-tenancy support and built a dashboard with analytics. Migrated a large-scale competitive intelligence app from Pug/Express.js to React + NestJS, improving page load speeds by 85%. Integrated Cerbos for fine-grained access control. Built fully isolated Dev, Staging, and Testing environments with CI/CD pipelines. Engineered RESTful APIs, built multi-agent automation workflows for PDF-to-PPT generation, and developed advanced Python-based AI deep-searching tools with fuzzy matching and semantic extraction.",
    type: "Full-time",
    createdAt: "2024-12-01T10:00:00.000Z",
    updatedAt: "2024-12-01T10:00:00.000Z",
  },
  {
    _id: "exp2",
    title: "Software Developer",
    company: "Tech Mahindra Ltd.",
    location: "Noida, India",
    period: "Nov 2021 - Aug 2024",
    description:
      "Spearheaded enhancements for AT&T projects including Orca (Warehouse Management) and Atlas (SRN Ticketing, WiFi Extenders EasyMesh, MultiCPE). Leveraged Angular, Node.js, Express.js, and MongoDB achieving 20% performance optimization. Designed full-stack applications driving 5% increase in user engagement. Implemented features reducing ticket resolution time from 3 days to 1 day. Oversaw both back-end and front-end development, increasing site performance by 25%. Implemented unit tests using Karma and Jasmine.",
    type: "Full-time",
    createdAt: "2021-11-01T10:00:00.000Z",
    updatedAt: "2021-11-01T10:00:00.000Z",
  },
  {
    _id: "exp3",
    title: "Software Developer Intern",
    company: "Group Bayport",
    location: "Remote",
    period: "Apr 2021 - Oct 2021",
    description:
      "Developed front-end components for BannerBuzz.com and coversandall.com, driving 35% increase in user engagement. Engineered and integrated React components into an existing design tool with Node.js, achieving 25% improvement in conversion rates. Enhanced existing software resulting in twofold enhancement of user experience. Produced efficient, modular code achieving 20% increase in efficiency.",
    type: "Internship",
    createdAt: "2021-04-01T10:00:00.000Z",
    updatedAt: "2021-04-01T10:00:00.000Z",
  },
]

export const fallbackEducation = [
  {
    _id: "edu1",
    institution: "Rawal Institute of Engineering and Technology",
    degree: "Bachelor of Technology in Computer Science and Engineering",
    field: "Computer Science and Engineering",
    location: "Faridabad, India",
    period: "2016 - 2020",
    description:
      "Affiliated by Maharishi Dayanand University. Grade: 65%.",
    type: "education",
    createdAt: "2016-08-01T10:00:00.000Z",
    updatedAt: "2016-08-01T10:00:00.000Z",
  },
]

export const fallbackFiles = [
  {
    _id: "fallback-file-1",
    name: "resume.pdf",
    url: "/placeholder.svg?height=800&width=600",
    type: "application/pdf",
    size: 1024000,
    createdAt: "2023-01-01T10:00:00.000Z",
    updatedAt: "2023-01-01T10:00:00.000Z",
  },
  {
    _id: "fallback-file-2",
    name: "profile-picture.jpg",
    url: "/placeholder.svg?height=400&width=400",
    type: "image/jpeg",
    size: 512000,
    createdAt: "2023-01-01T10:00:00.000Z",
    updatedAt: "2023-01-01T10:00:00.000Z",
  },
]

// For backward compatibility
export const fallbackExperiences = {
  work: fallbackWorkExperience,
  education: fallbackEducation,
}
